### ISSUE TITLE
Clicklisteners to the menu icons 

### ISSUE THREAD

**Issue by pkanyerezi** [Cleveroad/LoopBar#11]
Hey,

After using:
    <com.cleveroad.loopbar.widget.LoopBarView
        android:id="@+id/endlessView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:enls_placeholderId="@id/placeHolder"
        app:enls_orientation="horizontal"
        app:enls_selectionGravity="start"
        app:enls_selectionMargin="10dp"
        app:enls_overlaySize="5dp"
        app:enls_selectionInAnimation="@animator/enls_scale_restore"
        app:enls_selectionOutAnimation="@animator/enls_scale_small"
        app:enls_selectionBackground="@android:color/holo_blue_dark"
        app:enls_menu="@menu/loopbar"
        app:enls_scrollMode="auto"
        />

in my xml.

How do i set onclicklistener on the menu icon in my main activity.
Am really stuck here.
 thanks

**Comment by Iojjj** [comment]
Hi @pkanyerezi,

I guess it should be something like this:
```java
final LoopBarView loopBarView = findViewById(...);
...
loopBarView.addOnItemClickListener(new com.cleveroad.loopbar.widget.OnItemClickListener() {
    @Override
    public void onItemClicked(int position) {
        // item clicked
    }
});
```

**Comment by Iojjj** [comment]
@pkanyerezi, if my answer helped you, mark this issue as closed
