### ISSUE TITLE
use in sdk 15 

### ISSUE THREAD

**Issue by mbf5923** [Cleveroad/LoopBar#12]
hi 
how i can use loopbar in sdk 15? my app is released in min sdk 15 and i now will make chenge my buttom menu and i can't use minsdk 16

**Comment by mbf5923** [comment]
i download loopbar and change minsdk to 15 and just found one issue,
on LoopBarView line 229:
mViewColorable.setBackground(colorDrawable);

i change it to:

int sdk = android.os.Build.VERSION.SDK_INT;
        if(sdk < android.os.Build.VERSION_CODES.JELLY_BEAN) {
            mViewColorable.setBackgroundDrawable(colorDrawable);
        } else {
            mViewColorable.setBackground(colorDrawable);
        }

and work fine in sdk 15

**Comment by ValeryGes** [comment]
Hi @mbf5923, support for sdk 15 was added in version 1.1.2
