### ISSUE TITLE
Gravity

### ISSUE THREAD

**Issue by bhavna935** [Cleveroad/LoopBar#17]
I want to make the LoopBar Item gravity as center,For now its working for START and END.
Please help me how to achieve this?

**Comment by ValeryGes** [comment]
Hi @bhavna935! Thank you for your feedback. Do you mean the gravity of selector item? If yes, we definitely make this improvement in our future releases of LoopBar. There are some cases where we need to resolve to make this improvement. We need to understand what way for not infinite scrolling mode is best for center gravity selector and provide it. Also there can be problems with header and holder in recyclerView, so we need time to check it and fix. Unfortunately, I can say you exact date of next release, so if you want you can fork library and try to make this improvements by yourself.

If you mean the gravity in viewHolders in example, make free to write your own adapter and viewHolder with gravity you want.

With best regards,
Cleveroad team
