### ISSUE TITLE
selected tab view 'blinks'

### ISSUE THREAD

**Issue by ghost** [Cleveroad/LoopBar#18]
I ran the sample on my asus zenfone 2 , android 5.0 . When a tab is selected , icon and text of selected tab view blinks around 3 times . I'm not talking about the scale & alpha animation. Also , if I try to move to next fragment by swiping gesture when I am already at last page , icon and text completely dissapears and won't  be visible again. Any chance this can be fixed?

**Comment by Iojjj** [comment]
Hi @soad130,

we'll look into this problem once our developers will have a time. You can also help us by sending pull request with fixes if you fix this on your own. Just don't forget to make PR on **develop** branch.
