### ISSUE TITLE
How to use it in Xamarin.Android

### ISSUE THREAD

**Issue by jamsshhayd** [Cleveroad/LoopBar#19]
I have just watched a thread on stackoverflow, in the Answers section a person recommended this so I was curious to know how am I going to reference in my Xamarin Applications?

**Comment by Iojjj** [comment]
Quick research says that you need to use Binding of Java Library.

1. Download **.aar** file [here](http://www.mvnrepository.com/artifact/com.cleveroad/loopbar/1.1.3).
2. Check [this manual](https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/binding-an-aar/) and try follow its steps.

As alternative you can try to use [this plugin](https://marketplace.visualstudio.com/items?itemName=EgorBogatov.XamarinGradleBindings).

**Comment by jamsshhayd** [comment]
I managed to add the references and put the suggested xml element in the activity. But then suddenly this runtime exception occured that it is not going to get inflated. 

>** Android.Views.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class com.cleveroad.loopbar.widget.loopbarview**

![Here is a screenshot](https://cloud.githubusercontent.com/assets/16099439/24547988/336542cc-162c-11e7-8ad6-c36d6c1688c4.png)

**Comment by Iojjj** [comment]
We don't have expertise in Xamarin development, so you need to find the way how to run this (or any other) lib on your own. It would be great if you post your solution here for anyone who also interested in using this lib in Xamarin.

**Comment by jamsshhayd** [comment]
Sure, I will post the solution if I am able to find one.

**Comment by rolloqueritchie** [comment]
Hi @jamsshhayd, are you able to bind the LoopBar into your Xamarin applications? Thanks

**Comment by jamsshhayd** [comment]
@rolloqueritchie I had to move towards another thing because of a short deadline and I had used bottombar to achieve this feature.
