### ISSUE TITLE
Add support for ViewPager

### ISSUE THREAD

**Issue by PDDStudio** [Cleveroad/LoopBar#2]
It would be great if you could set up the LoopBar with a ViewPager and let it behave like TabLayout from the Support Design Library.
Any doubts of seeing this feature in a later version of LoopBar?

**Comment by woetao** [comment]
Error:E:\xcode\LeranA\app\src\main\AndroidManifest.xml:8:9-41 Error:
    Attribute application@label value=(@string/app_name) from AndroidManifest.xml:8:9-41
    is also present at [com.cleveroad:loopbar:1.0.0] AndroidManifest.xml:14:9-46 value=(@string/enls_app_name).
    Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:5:5-18:19 to override.
E:\xcode\LeranA\app\src\main\AndroidManifest.xml Error:
    uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.cleveroad:loopbar:1.0.0] E:\xcode\LeranA\app\build\intermediates\exploded-aar\com.cleveroad\loopbar\1.0.0\AndroidManifest.xml
    Suggestion: use tools:overrideLibrary="com.cleveroad.loopbar" to force usage
FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:processDebugManifest'.
  
  > Manifest merger failed with multiple errors, see logs
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Android studio 2.2.0preivew6 gradle verions2.2 preview 6

**Comment by felixcc** [comment]
What went wrong:
Execution failed for task ':app:processDebugManifest'.

**Comment by ilchenko-peter** [comment]
@PDDStudio This ability was added in 1.0.1
@woetao, @noblesky  crash was fixed in 1.0.1
