### ISSUE TITLE
disbale white background on change item animation

### ISSUE THREAD

**Issue by pishguy** [Cleveroad/LoopBar#23]
how can i change white background ?

please see this simple video (320kb)

http://www.mediafire.com/file/rn5zu3hx5qnujdv/video_2017-06-04_15-33-49.mp4

**Comment by yatsinskiyCR** [comment]
Hi @MahdiPishguy, Could you please show your xml and code?

**Comment by pishguy** [comment]
@yatsinskiyCR I'm so sorry, i removed that from project, my xml layout was copied from your sample code

**Comment by ValeryGes** [comment]
Hi, @MahdiPishguy!

Actually we can't reproduce this issue. So maybe you can help us, describe what you changed in layout copied from example and did you have this issue at some specific device?

**Comment by pishguy** [comment]
@ValeryGes i'm waiting to release new version of this useful library, let me to test that after that
