### ISSUE TITLE
use loop bar on right side

### ISSUE THREAD

**Issue by pishguy** [Cleveroad/LoopBar#24]
how can i have loop bar as vertical with right position? by default loop bar is left side, how can i change that?

**Comment by ValeryGes** [comment]
Hi, @MahdiPishguy! 

Sorry for late answer and thank you for using our library.
We will provide a new version of loopbar with right and top position soon. Just wait for it.

With best regards, Cleveroad team.

**Comment by yarovoiag** [comment]
Thanks for waiting. New version 1.1.4 is already published.

**Comment by pishguy** [comment]
@yarovoiag thank you very much
